let gameData = [
    {
        "role": "00 | GAMEPLAY PROGRAMMER & GAME DESIGNER",
        "image": "assets/Absolute Minima.png",
        "alt": "Linea being held on puppet strings.",
        "title": "Absolute Minima",
        "description": "This minimalist roguelike follows Linea, a hand-drawn character, as she attempts to escape the sketchbook world her creator has trapped her in.",
        "release": "Coming 2025",
        "genre1": "Roguelike",
        "genre2": "Dungeon Crawler",
        "genre3": "Adventure",
        "tech1": "Unity",
        "tech2": "C#",
        "link": "#",
        "customOrder": 3,
        "dateOrder": 0
    },
    {
        "role": "01 | GAMEPLAY PROGRAMMER & TEAM LEAD",
        "image": "assets/CPU City.jpg",
        "alt": "Rhi standing in CPU City staring in the distance",
        "title": "CPU City",
        "description": "Guide Rhi Vyse through a vibrant city as you master Von Neumann Architecture and thwart the Pro-Krastor Nation's plans. Built in a team of 4.",
        "release": "August 2024",
        "genre1": "Third Person",
        "genre2": "Adventure",
        "genre3": "Education",
        "tech1": "Unity",
        "tech2": "C#",
        "link": "https://kylejussab.com/cpucity",
        "customOrder": 1,
        "dateOrder": 1
    },
    {
        "role": "02 | GAMEPLAY PROGRAMMER & GAME DESIGNER",
        "image": "assets/The Last of Us Between The Years Page Cover.png",
        "alt": "Joel looking in the distance",
        "title": "The Last of Us: Between The Years",
        "description": "This Gameboy game explores Joel's character and grief during the 20 years between Sarah's death and the main events of the first game.",
        "release": "June 2024",
        "genre1": "Side Scroller",
        "genre2": "Action",
        "genre3": "Adventure",
        "tech1": "GB Studio",
        "tech2": "GBVM",
        "link": "https://kylejussab.com/tloubty",
        "customOrder": 0,
        "dateOrder": 2
    },
    // {
    //     "techStack": "Unity, C#",
    //     "image": "assets/tah2.png",
    //     "alt": "Elian crouched over",
    //     "title": "The Architect Hestia",
    //     "subtitle": "Third Person Shooter / Survival / Adventure - Coming soon",
    //     "description": "Elian, a Rusthavener, is tired of the opression forced on him by Auravale. Little does he know, with each death he switches sides.",
    //     "link": "https://kylejussab.com/thearchitecthestia"
    // },
    {
        "role": "03 | GAMEPLAY PROGRAMMER & GAME DESIGNER",
        "image": "assets/pp2.png",
        "alt": "A ball on a tower",
        "title": "Project Phoebe",
        "description": "Master your skills getting through rooms by competing in 5 different modes, all of which challenge you in a different and unique way.",
        "release": "April 2023",
        "genre1": "Third Person",
        "genre2": "Platformer",
        "genre3": "Puzzler",
        "tech1": "Unity",
        "tech2": "C#",
        "link": "https://kylejussab.com/projectphoebe",
        "customOrder": 2,
        "dateOrder": 3
    }
];

let projectData = [
    {
        "isCollection": true,
        "projects": [{name: "The Last Stand", description: "To be announced"}, {name: "Between the Years", description: "A game about Joel on the GameBoy"}, {name: "The Data of Us", description: "A data exploration of Part II"}],
        "role": "04 | DESIGNER & DEVELOPER",
        "image": "assets/Tribute Trilogy.png",
        "alt": "Three Last of Us themed images fading into each other",
        "title": "The Last of Us: Tribute Trilogy",
        "description": "A collection of my fan-made projects that explore The Last of Us through my personal lens.",
        "date": "Coming 2025",
        "tech1": "Unity / GB Studio",
        "tech2": "Python",
        "discipline1": "Game Dev",
        "discipline2": "Data Science",
        "discipline3": "Fan Projects",
        "link": "#",
        "customOrder": 3,
        "dateOrder": 0
    },
    {
        "role": "01 | FRONTEND DEVELOPER",
        "image": "assets/Give Fund.png",
        "alt": "A title screen showing the text Give Fund",
        "title": "Give Fund",
        "description": "A fundraising feature to help foster youth non-profits raise funds from Snap users, built off a mock up of the Snapchat App. Built in a cross-functional team of 7 and presented to over 300 Snap executives.",
        "date": "August 2024",
        "tech1": "React Native",
        "tech2": "Supabase",
        "discipline1": "Mobile Dev",
        "discipline2": "UI / UX",
        "discipline3": "Product Design",
        "link": "https://kylejussab.com/givefund",
        "customOrder": 1,
        "dateOrder": 1
    },
    {
        "role": "02 | RESEARCHER",
        "image": "assets/The Data of Us.png",
        "alt": "A word cloud of a Clicker",
        "title": "The Data of Us",
        "description": "A data-driven investigation into the success and controversy of The Last of Us Part II using sentiment analysis, sales data, award history, and critical comparisons to explore how and why the sequel became one of the most divisive games in modern history.",
        "date": "January 2024",
        "tech1": "Python",
        "tech2": "NLTK",
        "discipline1": "Data Science",
        "discipline2": "Engineering",
        "discipline3": "Automation",
        "link": "https://kylejussab.com/dataofus",
        "customOrder": 0,
        "dateOrder": 2
    },
    {
        "role": "03 | FRONTEND DEVELOPER",
        "image": "assets/PixelPulse Cover Art.png",
        "alt": "The homepage of the PixelPulse application",
        "title": "PixelPulse",
        "description": "A 'social media' platform for UoL Computer Science students to share their coding projects. Used for inspiration and revision. Built in a team of 4 using Agile methodologies.",
        "date": "September 2023",
        "tech1": "HTML / CSS",
        "tech2": "JavaScript",
        "discipline1": "Web Dev",
        "discipline2": "UI / UX",
        "discipline3": "Research",
        "link": "https://kylejussab.com/pixelpulse",
        "customOrder": 2,
        "dateOrder": 3
    }
]